name: Build project

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential gcc-14 cmake

      - name: Debug
        run: make debug

      - name: Release
        run: make release

      - name: Upload Debug Artifact
        uses: actions/upload-artifact@v4
        with:
           name: linux-x86_64-debug
           path: build/debug/bin

      - name: Upload Release Artifact
        uses: actions/upload-artifact@v4
        with:
           name: linux-x86_64-release
           path: build/release/bin